name: DieLigaDerKeks
version: 0.0.1
main: org.zimbls.DieLigaDerKeks.DieLigaDerKeks
api-version: 1.20

commands:
  liga:
    description: Starts the game
    usage: /liga start
  ready:
    description: Marks a player as ready
    usage: /ready
  points:
    description: Displays the points when you are in a game
    usage: /points
  vote:
    description: Vote for current event
    usage: /vote
  language:
    description: Change the language
    usage: /language [en|de]
  revive:
    description: Revive a dead participant
    usage: /revive <player name>